#!/bin/bash
# Execution Changelog Generator (Safety Net Hook)
# Runs at session Stop to ensure changelogs exist in artifacts
# The execution skill creates detailed changelogs; this is a fallback

# Only run if we're in a code-build context
CODEBUILD_DIR=".code-build"
if [ ! -d "$CODEBUILD_DIR" ]; then
    echo '{"continue": true, "suppressOutput": true}'
    exit 0
fi

# Check if artifacts directory exists
ARTIFACTS_DIR="$CODEBUILD_DIR/artifacts"
if [ ! -d "$ARTIFACTS_DIR" ]; then
    echo '{"continue": true, "suppressOutput": true}'
    exit 0
fi

# Find the most recent agent instance folder
LATEST_AGENT=$(ls -td "$ARTIFACTS_DIR"/agent_* 2>/dev/null | head -1)
if [ -z "$LATEST_AGENT" ]; then
    echo '{"continue": true, "suppressOutput": true}'
    exit 0
fi

EXEC_DIR="$LATEST_AGENT/execution"
if [ ! -d "$EXEC_DIR" ]; then
    echo '{"continue": true, "suppressOutput": true}'
    exit 0
fi

# Check if a changelog was already created recently (within 5 minutes)
LATEST_CHANGELOG=$(ls -t "$EXEC_DIR"/changelog_*.txt 2>/dev/null | head -1)
if [ -n "$LATEST_CHANGELOG" ]; then
    LATEST_MOD=$(date -r "$LATEST_CHANGELOG" +%s 2>/dev/null)
    CURRENT_TIME=$(date +%s)
    if [ -n "$LATEST_MOD" ]; then
        DIFF=$((CURRENT_TIME - LATEST_MOD))
        if [ "$DIFF" -lt 300 ]; then
            echo '{"continue": true, "suppressOutput": true}'
            exit 0
        fi
    fi
fi

# Generate a safety-net changelog
TIMESTAMP=$(date +"%d%m%Y_%H%M")
CHANGELOG_FILE="$EXEC_DIR/changelog_${TIMESTAMP}.txt"

GIT_LOG=$(git log --oneline -20 2>/dev/null || echo "No git history available")
GIT_DIFF_STAT=$(git diff --stat HEAD~1 2>/dev/null || echo "No diff available")
CHANGED_FILES=$(git diff --name-only HEAD~1 2>/dev/null || echo "No changes detected")

cat > "$CHANGELOG_FILE" << CHANGELOG_EOF
====================================================
EXECUTION CHANGELOG (Auto-generated safety net)
Date: $(date +"%d/%m/%Y %H:%M")
Agent: $(basename "$LATEST_AGENT")
====================================================

RECENT COMMITS
--------------
$GIT_LOG

FILES CHANGED
-------------
$GIT_DIFF_STAT

CHANGED FILE LIST
-----------------
$CHANGED_FILES

====================================================
NOTE: This was auto-generated by the hook.
The execution skill generates a more detailed version.
====================================================
CHANGELOG_EOF

echo "{\"continue\": true, \"suppressOutput\": false, \"systemMessage\": \"Safety-net changelog saved to $CHANGELOG_FILE\"}"
exit 0